### ISSUE TITLE
BIRD only spots deleted local routes during kernel scan

### ISSUE THREAD

**Issue by eepyaich** [projectcalico/networking-calico#19]
BIRD uses Netlink sockets to get notifications of changes to the kernel routing tables.  This means it will be notified immediately of any new routes that Felix programs.  However, routes are removed from the kernel, BIRD ignores the notification ( see comment in krt_got_route_async() about "echo of our deletion").

The upshot is that when Calico removes a route, it could take up to the configured BIRD kernel scan time before the corresponding route withdraw is sent.  In a migration case, this will cause latency in the VM migration.  It also means that we require the BIRD scan time to be set relatively low (which then has an impact on CPU load).

We should modify BIRD so that it correctly acts on the route delete notification.

**Comment by fasaxc** [comment]
This has been open for a long time with no reinforcement from our OpenStack user base.  Let's close it.
