### ISSUE TITLE
networking-calico RPM requires python2-etcd3gw

### ISSUE THREAD

**Issue by ntaylor1781** [projectcalico/networking-calico#53]
The documentation states to pip3 install a specific commit of etcd3gw, but the new versions of the RPM still require python2-etcd3gw. This becomes an issue with newer OpenStack releases that require python3 (and don't have python2). Since we are expected to handle the install through pip, it seems we could get rid of the requirement in the RPM spec. 

I'm happy to put together a PR (it's only a one line change), but figured I would open an issue first.

**Comment by nelljerram** [comment]
Thank you @ntaylor1781 , you're quite right.  Please do post the PR.
