### ISSUE TITLE
icmp6 type and code fields are not set correct in security group.

### ISSUE THREAD

**Issue by Molnigt** [projectcalico/networking-calico#7]
#5 #6  
Calico 3.12
Openstack Train
When making a specific icmp6 type/code rule it doesn't pass validation. It gets rejected because it is stored as a port range which will fail.

`[{"action": "Allow", "ipVersion": 6, "destination": {"ports": ["128:1"]}, "protocol": "ICMPv6", "source": {"nets": ["::/0"]}},`

`minimum port number (128) is greater than maximum port number (1) in port range`

**Comment by nelljerram** [comment]
@Molnigt I believe this has now been fixed by #5 and #6 - is that right?

**Comment by Molnigt** [comment]
Yes, it works fine for us.

**Comment by nelljerram** [comment]
Many thanks @Molnigt !
